//! Input-derived form builders. Controls render their own generated names;
//! completion requires every declared field, including fields with serde defaults.
use axum::{
    body::Bytes,
    extract::{FromRequest, Request},
    http::{Method, StatusCode, header},
    response::{IntoResponse, Response},
};
use maud::{Markup, PreEscaped, html};
use serde::{Serialize, de::DeserializeOwned};
use std::{collections::HashMap, fmt::Display, marker::PhantomData};

#[doc = include_str!("../docs/typed-forms.md")]
pub trait FormInput: DeserializeOwned + Sized + 'static {
    type Builder: private::FormBuilder<Input = Self>;
    fn fields() -> Self::Builder;
    /// Wire names and absence rules, in declaration order. Generated by the derive.
    #[doc(hidden)]
    const FIELDS: &'static [(&'static str, private::Absent)];
}

/// A completed form for exactly one payload type. Constructed by finish() on
/// an input-derived builder after every field has been emitted once.
pub struct FormFields<I> {
    markup: Markup,
    base: String,
    input: PhantomData<fn() -> I>,
}

impl<I> FormFields<I> {
    pub(crate) fn into_markup(self) -> Markup {
        self.markup
    }

    /// The markup and the encoded [`BASE`] of its visible controls.
    pub(crate) fn into_parts(self) -> (Markup, String) {
        (self.markup, self.base)
    }
}

/// Form field names with this prefix belong to Placebo. The adapters remove
/// them before decoding, and payload fields cannot use them.
pub(crate) const RESERVED: &str = "placebo-";

/// A mutation form's hidden field with a hash of each visible control's
/// rendered value. A native submission compares it with the submitted values
/// to find the fields the person edited, the same rule the runtime uses.
pub(crate) const BASE: &str = "placebo-base";

/// The page a form is on, rendered only when the address shows another path:
/// on a page rendered for a native submission. See `native::current_page`.
pub(crate) const PAGE: &str = "placebo-page";

/// A short fingerprint of the values a field submits. Browsers submit
/// textarea line breaks as CRLF; the rendered defaults use LF.
fn fingerprint(values: &[impl AsRef<str>]) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for value in values {
        let value = value.as_ref().replace("\r\n", "\n").replace('\r', "\n");
        for byte in format!("{}:{value}\n", value.len()).bytes() {
            hash ^= u64::from(byte);
            hash = hash.wrapping_mul(0x0100_0000_01b3);
        }
    }
    format!("{hash:016x}")
}

/// The submitted values of the fields a native submission changed from the
/// values its form was rendered with.
fn edited_fields<I: FormInput>(pairs: &[(String, String)]) -> HashMap<String, crate::native::Edit> {
    let Some((_, base)) = pairs.iter().find(|(key, _)| key == BASE) else {
        return HashMap::new();
    };
    let base: HashMap<String, String> = form_urlencoded::parse(base.as_bytes())
        .into_owned()
        .collect();
    I::FIELDS
        .iter()
        .filter_map(|(name, _)| {
            let rendered = base.get(*name)?;
            let values: Vec<String> = pairs
                .iter()
                .filter(|(key, _)| key == name)
                .map(|(_, value)| value.clone())
                .collect();
            (fingerprint(&values) != *rendered).then(|| {
                let base = rendered.clone();
                ((*name).to_owned(), crate::native::Edit { values, base })
            })
        })
        .collect()
}

/// Rustc may report any trait in the chain for an unsupported field type, so
/// each one carries the same explanation.
macro_rules! field_type_trait {
    ($item:item) => {
        #[diagnostic::on_unimplemented(
            message = "`{Self}` is not a supported form field type",
            note = "form fields can be String, bool, integers, floats, #[derive(FormEnum)] enums, or Option<T> or Vec<T> of those"
        )]
        $item
    };
}

mod sealed {
    field_type_trait!(
        pub trait Value {}
    );
    field_type_trait!(
        pub trait Field {}
    );
}

field_type_trait! {
    /// A scalar submitted as one form value: `String`, `bool`, integers, floats, or
    /// an enum with `#[derive(FormEnum)]`. `Option` and `Vec` of these are fields too.
    pub trait FieldValue: sealed::Value + DeserializeOwned {
        #[doc(hidden)]
        const ABSENT: private::Absent;
        #[doc(hidden)]
        fn encode(&self) -> String;
    }
}

/// A unit-only enum usable as a form value. Derive it with `#[derive(FormEnum)]`
/// alongside serde's `Serialize` and `Deserialize`: the submitted value is the
/// variant's serde name, so `rename` and `rename_all` apply to forms as well.
pub trait FormEnum: Serialize + DeserializeOwned + private::EnumSeal {}

field_type_trait! {
    /// Every supported payload field type: a [`FieldValue`], an `Option` of one
    /// (an empty or absent submission is `None`), or a `Vec` of one (repeated submissions).
    pub trait FormValue: sealed::Field + DeserializeOwned {
        #[doc(hidden)]
        const ABSENT: private::Absent;
    }
}

/// A value submitted once by a single control: a scalar, or an optional scalar
/// encoded as an empty string when `None`.
pub trait SingleValue: FormValue {
    #[doc(hidden)]
    fn encode(&self) -> String;
}

/// Values for text-like inputs: `String`, or `Option<String>` where empty is `None`.
pub trait TextValue: SingleValue {}

/// Values for number inputs: integers, floats, or an optional one.
pub trait NumberValue: SingleValue {
    /// The attribute type for `min`, `max`, and `step`.
    type Number: Display;
    #[doc(hidden)]
    const STEP: Option<&'static str>;
}

impl<T: FieldValue> sealed::Field for T {}
impl<T: FieldValue> FormValue for T {
    const ABSENT: private::Absent = <T as FieldValue>::ABSENT;
}
impl<T: FieldValue> SingleValue for T {
    fn encode(&self) -> String {
        FieldValue::encode(self)
    }
}
impl<T: FieldValue> sealed::Field for Option<T> {}
impl<T: FieldValue> FormValue for Option<T> {
    const ABSENT: private::Absent = private::Absent::None;
}
impl<T: FieldValue> SingleValue for Option<T> {
    fn encode(&self) -> String {
        self.as_ref().map(FieldValue::encode).unwrap_or_default()
    }
}
impl<T: FieldValue> sealed::Field for Vec<T> {}
impl<T: FieldValue> FormValue for Vec<T> {
    const ABSENT: private::Absent = private::Absent::Empty;
}

macro_rules! scalars {
    ($absent:ident: $($ty:ty),* $(,)?) => { $(
        impl sealed::Value for $ty {}
        impl FieldValue for $ty {
            const ABSENT: private::Absent = private::Absent::$absent;
            fn encode(&self) -> String { self.to_string() }
        }
    )* };
}
scalars!(Required: String, u8, u16, u32, u64, usize, i8, i16, i32, i64, isize, f32, f64);
// An unchecked checkbox submits nothing, so an absent bool decodes as false.
scalars!(False: bool);

impl<T: FormEnum> sealed::Value for T {}
impl<T: FormEnum> FieldValue for T {
    const ABSENT: private::Absent = private::Absent::Required;
    fn encode(&self) -> String {
        match serde_json::to_value(self) {
            Ok(serde_json::Value::String(name)) => name,
            _ => panic!("a FormEnum must serialize as a unit variant name"),
        }
    }
}

impl TextValue for String {}
impl TextValue for Option<String> {}

macro_rules! numbers {
    ($step:expr => $($ty:ty),* $(,)?) => { $(
        impl NumberValue for $ty { type Number = $ty; const STEP: Option<&'static str> = $step; }
        impl NumberValue for Option<$ty> { type Number = $ty; const STEP: Option<&'static str> = $step; }
    )* };
}
numbers!(None => u8, u16, u32, u64, usize, i8, i16, i32, i64, isize);
// Browsers otherwise reject fractional values against the default step of 1.
numbers!(Some("any") => f32, f64);

enum Kind {
    Hidden(String),
    Text(String, &'static str),
    TextArea(String),
    Number(String),
    Checkbox(bool),
    Select(Vec<(String, String, bool)>),
    MultiSelect(Vec<(String, String, bool)>),
    Radios(Vec<(String, String, bool)>),
    Checkboxes(Vec<(String, String, bool)>),
}

/// A control with a payload value type. The builder supplies its field name;
/// there is no name override or disabled option that could remove it from submission.
pub struct Control<T> {
    kind: Kind,
    id: Option<String>,
    class: Option<String>,
    described_by: Option<String>,
    autocomplete: Option<String>,
    placeholder: Option<String>,
    rows: Option<u32>,
    min: Option<String>,
    max: Option<String>,
    step: Option<String>,
    required: bool,
    max_length: Option<u32>,
    invalid: bool,
    autofocus: bool,
    value: PhantomData<fn() -> T>,
}

impl<T> Control<T> {
    fn new(kind: Kind) -> Self {
        Self {
            kind,
            id: None,
            class: None,
            described_by: None,
            autocomplete: None,
            placeholder: None,
            rows: None,
            min: None,
            max: None,
            step: None,
            required: false,
            max_length: None,
            invalid: false,
            autofocus: false,
            value: PhantomData,
        }
    }

    /// The browser refuses to submit the form while this control is empty.
    /// For radios it applies to every button; a checkbox group cannot be required.
    pub fn required(mut self) -> Self {
        assert!(
            !matches!(self.kind, Kind::Hidden(_) | Kind::Checkboxes(_)),
            "required does not apply to hidden controls or checkbox groups"
        );
        self.required = true;
        self
    }

    /// The most characters the browser lets someone type.
    pub fn max_length(mut self, length: u32) -> Self {
        assert!(
            matches!(self.kind, Kind::Text(..) | Kind::TextArea(_)),
            "max_length applies to text and textarea controls"
        );
        self.max_length = Some(length);
        self
    }

    /// Mark the control `aria-invalid` when the server rejected its value.
    /// Link the message with `described_by`. An invalid reply moves focus to
    /// the first invalid control, and the mark follows the server even while
    /// the control keeps its unsaved value.
    pub fn invalid(mut self, invalid: bool) -> Self {
        assert!(
            !matches!(self.kind, Kind::Hidden(_)),
            "a hidden control cannot be marked invalid"
        );
        self.invalid = invalid;
        self
    }

    /// For grouped controls (radios and checkboxes), this applies to the group element.
    pub fn id(mut self, id: &str) -> Self {
        self.id = Some(id.into());
        self
    }
    pub fn class(mut self, class: &str) -> Self {
        self.class = Some(class.into());
        self
    }
    pub fn described_by(mut self, id: &str) -> Self {
        self.described_by = Some(id.into());
        self
    }
    pub fn autocomplete(mut self, value: &str) -> Self {
        assert!(
            matches!(
                self.kind,
                Kind::Text(..) | Kind::TextArea(_) | Kind::Number(_) | Kind::Select(_)
            ),
            "autocomplete applies to text, textarea, number, and select controls"
        );
        self.autocomplete = Some(value.into());
        self
    }
    pub fn placeholder(mut self, value: &str) -> Self {
        assert!(
            matches!(
                self.kind,
                Kind::Text(..) | Kind::TextArea(_) | Kind::Number(_)
            ),
            "placeholder applies to text, textarea, and number controls"
        );
        self.placeholder = Some(value.into());
        self
    }
    pub fn rows(mut self, rows: u32) -> Self {
        assert!(
            matches!(self.kind, Kind::TextArea(_)),
            "rows applies to textarea controls"
        );
        self.rows = Some(rows);
        self
    }

    /// The values this control submits as rendered, for [`BASE`]. Hidden
    /// controls always follow the server and passwords are never echoed, so
    /// neither takes part.
    fn rendered_values(&self) -> Option<Vec<String>> {
        let chosen = |options: &[(String, String, bool)]| {
            options
                .iter()
                .filter(|(_, _, chosen)| *chosen)
                .map(|(value, _, _)| value.clone())
                .collect()
        };
        Some(match &self.kind {
            Kind::Hidden(_) | Kind::Text(_, "password") => return None,
            Kind::Text(value, _) | Kind::TextArea(value) | Kind::Number(value) => {
                vec![value.clone()]
            }
            Kind::Checkbox(checked) => {
                if *checked {
                    vec!["true".to_owned()]
                } else {
                    Vec::new()
                }
            }
            // A single select submits its last selected option.
            Kind::Select(options) => {
                let selected: Vec<String> = chosen(options);
                selected.last().cloned().into_iter().collect()
            }
            Kind::MultiSelect(options) | Kind::Radios(options) | Kind::Checkboxes(options) => {
                chosen(options)
            }
        })
    }

    /// Show the values a native submission sent for this edited field.
    fn resubmit(&mut self, values: &[String]) {
        let choose = |options: &mut Vec<(String, String, bool)>| {
            if options.iter().any(|(value, _, _)| values.contains(value)) {
                for (value, _, chosen) in options {
                    *chosen = values.contains(value);
                }
            }
        };
        let first = values.first().cloned().unwrap_or_default();
        match &mut self.kind {
            Kind::Hidden(_) | Kind::Text(_, "password") => {}
            Kind::Text(value, _) | Kind::TextArea(value) | Kind::Number(value) => *value = first,
            Kind::Checkbox(checked) => *checked = !values.is_empty(),
            Kind::Select(options)
            | Kind::MultiSelect(options)
            | Kind::Radios(options)
            | Kind::Checkboxes(options) => choose(options),
        }
    }

    #[doc(hidden)]
    pub fn render_named(self, name: &str) -> Markup {
        let Self {
            kind,
            id,
            class,
            described_by,
            autocomplete,
            placeholder,
            rows,
            min,
            max,
            step,
            required,
            max_length,
            invalid,
            autofocus,
            ..
        } = self;
        // Every visible control is its own retained unit, keyed by field name,
        // so a reply keeps its unsaved edits and replaces everything around it.
        let field = name;
        let invalid = invalid.then_some("true");
        match kind {
            Kind::Hidden(value) => html! { input type="hidden" name=(name) value=(value); },
            Kind::Text(value, kind) => html! {
                input type=(kind) name=(name) value=(value) id=[id] class=[class] autofocus[autofocus] required[required]
                    maxlength=[max_length] aria-invalid=[invalid] aria-describedby=[described_by]
                    autocomplete=[autocomplete] placeholder=[placeholder] data-placebo-field=(field);
            },
            // The parser drops one newline after <textarea>, so emit our own to keep a leading one.
            Kind::TextArea(value) => html! {
                textarea name=(name) id=[id] class=[class] rows=[rows] autofocus[autofocus] required[required] maxlength=[max_length]
                    aria-invalid=[invalid] aria-describedby=[described_by] autocomplete=[autocomplete]
                    placeholder=[placeholder] data-placebo-field=(field) { "\n" (value) }
            },
            Kind::Number(value) => html! {
                input type="number" name=(name) value=(value) min=[min] max=[max] step=[step]
                    id=[id] class=[class] autofocus[autofocus] required[required] aria-invalid=[invalid] aria-describedby=[described_by]
                    autocomplete=[autocomplete] placeholder=[placeholder] data-placebo-field=(field);
            },
            Kind::Checkbox(checked) => html! {
                input type="checkbox" name=(name) value="true" checked[checked] id=[id] class=[class]
                    autofocus[autofocus] required[required] aria-invalid=[invalid] aria-describedby=[described_by] data-placebo-field=(field);
            },
            Kind::Select(options) => html! {
                select name=(name) id=[id] class=[class] autofocus[autofocus] required[required] aria-invalid=[invalid]
                    aria-describedby=[described_by] autocomplete=[autocomplete] data-placebo-field=(field) {
                    @for (value, label, selected) in options {
                        option value=(value) selected[selected] { (label) }
                    }
                }
            },
            Kind::MultiSelect(options) => html! {
                select multiple name=(name) id=[id] class=[class] autofocus[autofocus] required[required] aria-invalid=[invalid]
                    aria-describedby=[described_by] data-placebo-field=(field) {
                    @for (value, label, selected) in options {
                        option value=(value) selected[selected] { (label) }
                    }
                }
            },
            Kind::Radios(options) => html! {
                div role="radiogroup" id=[id] class=[class] aria-required=[required.then_some("true")]
                    aria-invalid=[invalid] aria-describedby=[described_by] data-placebo-field=(field) {
                    @for (i, (value, label, checked)) in options.into_iter().enumerate() {
                        label { input type="radio" name=(name) value=(value) checked[checked] autofocus[autofocus && i == 0] required[required]; " " (label) }
                    }
                }
            },
            Kind::Checkboxes(options) => html! {
                div role="group" id=[id] class=[class] aria-invalid=[invalid] aria-describedby=[described_by]
                    data-placebo-field=(field) {
                    @for (i, (value, label, checked)) in options.into_iter().enumerate() {
                        label { input type="checkbox" name=(name) value=(value) checked[checked] autofocus[autofocus && i == 0]; " " (label) }
                    }
                }
            },
        }
    }
}

fn options<T: SingleValue + PartialEq, L: Into<String>>(
    options: impl IntoIterator<Item = (T, L)>,
    selected: impl Fn(&T) -> bool,
) -> Vec<(String, String, bool)> {
    options
        .into_iter()
        .map(|(value, label)| {
            let is_selected = selected(&value);
            (value.encode(), label.into(), is_selected)
        })
        .collect()
}

fn is_none<T: SingleValue>(value: &T) -> bool {
    matches!(T::ABSENT, private::Absent::None) && value.encode().is_empty()
}

impl<T: SingleValue> Control<T> {
    pub fn hidden(value: T) -> Self {
        Self::new(Kind::Hidden(value.encode()))
    }

    pub fn select<L: Into<String>>(selected: T, options: impl IntoIterator<Item = (T, L)>) -> Self
    where
        T: PartialEq,
    {
        let options = self::options(options, |value| *value == selected);
        assert!(
            options.iter().any(|(_, _, selected)| *selected),
            "a select needs an option matching its initial value"
        );
        Self::new(Kind::Select(options))
    }

    /// One labeled radio button per option, inside a `radiogroup` element.
    /// An optional field may start as `None` with no option checked.
    pub fn radios<L: Into<String>>(selected: T, options: impl IntoIterator<Item = (T, L)>) -> Self
    where
        T: PartialEq,
    {
        let options = self::options(options, |value| *value == selected);
        assert!(
            is_none(&selected) || options.iter().any(|(_, _, selected)| *selected),
            "radios need an option matching their initial value"
        );
        Self::new(Kind::Radios(options))
    }
}

impl<T: TextValue> Control<T> {
    pub fn text(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "text")
    }
    pub fn search(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "search")
    }
    pub fn email(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "email")
    }
    pub fn url(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "url")
    }
    pub fn tel(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "tel")
    }
    /// A `YYYY-MM-DD` string; parse and validate it in the handler.
    pub fn date(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "date")
    }
    /// An `HH:MM` or `HH:MM:SS` string.
    pub fn time(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "time")
    }
    /// A `YYYY-MM-DDTHH:MM` string without a time zone.
    pub fn datetime_local(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "datetime-local")
    }
    /// Always renders empty: a server response never echoes a password into markup.
    pub fn password() -> Self {
        Self::new(Kind::Text(String::new(), "password"))
    }
    pub fn textarea(value: impl Into<T>) -> Self {
        Self::new(Kind::TextArea(value.into().encode()))
    }

    fn text_kind(value: T, kind: &'static str) -> Self {
        Self::new(Kind::Text(value.encode(), kind))
    }
}

impl<T: NumberValue> Control<T> {
    /// Float fields default to `step="any"`; integer fields use the browser's step of 1.
    /// A number that is not an `Option` is `required`: an empty submission
    /// would fail decoding before the handler could answer with a message.
    pub fn number(value: T) -> Self {
        let mut control = Self::new(Kind::Number(value.encode()));
        control.step = T::STEP.map(Into::into);
        control.required = !matches!(T::ABSENT, private::Absent::None);
        control
    }
    pub fn min(mut self, value: T::Number) -> Self {
        self.assert_number();
        self.min = Some(value.to_string());
        self
    }
    pub fn max(mut self, value: T::Number) -> Self {
        self.assert_number();
        self.max = Some(value.to_string());
        self
    }
    pub fn step(mut self, value: T::Number) -> Self {
        self.assert_number();
        self.step = Some(value.to_string());
        self
    }

    fn assert_number(&self) {
        assert!(
            matches!(self.kind, Kind::Number(_)),
            "min, max, and step apply to number controls"
        );
    }
}

impl Control<bool> {
    /// Submits `true` when checked. An unchecked box submits nothing, which the
    /// typed adapters decode as `false`.
    pub fn checkbox(checked: bool) -> Self {
        Self::new(Kind::Checkbox(checked))
    }
}

impl<T: FieldValue + PartialEq> Control<Vec<T>> {
    /// A `<select multiple>`. Every selected value must be one of the options.
    pub fn multi_select<L: Into<String>>(
        selected: impl IntoIterator<Item = T>,
        options: impl IntoIterator<Item = (T, L)>,
    ) -> Self {
        Self::new(Kind::MultiSelect(many(selected, options)))
    }

    /// One labeled checkbox per option, inside a `group` element.
    pub fn checkboxes<L: Into<String>>(
        selected: impl IntoIterator<Item = T>,
        options: impl IntoIterator<Item = (T, L)>,
    ) -> Self {
        Self::new(Kind::Checkboxes(many(selected, options)))
    }
}

fn many<T: SingleValue + PartialEq, L: Into<String>>(
    selected: impl IntoIterator<Item = T>,
    options: impl IntoIterator<Item = (T, L)>,
) -> Vec<(String, String, bool)> {
    let selected: Vec<T> = selected.into_iter().collect();
    let options = self::options(options, |value| selected.contains(value));
    assert_eq!(
        options.iter().filter(|(_, _, selected)| *selected).count(),
        selected.len(),
        "every selected value needs exactly one matching option"
    );
    options
}

/// The action's typed payload, decoded with the same rules as its form fields.
/// Take it as the handler's last argument, after any other Axum extractors:
///
/// ```
/// use axum::extract::State;
/// use placebo::{FormInput, Input, MutationAction};
/// #[derive(serde::Deserialize, FormInput)]
/// struct Save { title: String }
/// const SAVE: MutationAction<Save> = MutationAction::new("save", "/save");
/// async fn save(State(db): State<()>, Input(input): Input<Save>) -> String {
///     input.title
/// }
/// let route: axum::routing::MethodRouter<()> = SAVE.route(save);
/// ```
///
/// GET and HEAD requests decode the query string and reject with 400, like
/// axum's `Query`. Other methods decode an urlencoded body and reject like
/// axum's `Form`: 415 for another content type, 422 for an undecodable payload.
pub struct Input<I>(pub I);

impl<I: FormInput, S: Send + Sync> FromRequest<S> for Input<I> {
    type Rejection = Response;

    async fn from_request(request: Request, state: &S) -> Result<Self, Self::Rejection> {
        if matches!(*request.method(), Method::GET | Method::HEAD) {
            return decode(request.uri().query().unwrap_or_default().as_bytes())
                .map(Self)
                .map_err(|error| {
                    (
                        StatusCode::BAD_REQUEST,
                        format!("Failed to deserialize query string: {error}"),
                    )
                        .into_response()
                });
        }
        let form = request
            .headers()
            .get(header::CONTENT_TYPE)
            .and_then(|value| value.to_str().ok())
            .and_then(|value| value.split(';').next())
            .is_some_and(|mime| {
                mime.trim()
                    .eq_ignore_ascii_case("application/x-www-form-urlencoded")
            });
        if !form {
            return Err((
                StatusCode::UNSUPPORTED_MEDIA_TYPE,
                "Expected request with `Content-Type: application/x-www-form-urlencoded`",
            )
                .into_response());
        }
        let path = request.uri().path().to_owned();
        let headers = request.headers().clone();
        let store = crate::replay::store(request.extensions());
        let body = Bytes::from_request(request, state)
            .await
            .map_err(IntoResponse::into_response)?;
        let pairs: Vec<(String, String)> = form_urlencoded::parse(&body).into_owned().collect();
        let field = |name: &str| {
            pairs
                .iter()
                .find(|(key, _)| key == name)
                .map(|(_, value)| value.as_str())
        };
        crate::native::record_submission::<I>(field(PAGE), edited_fields::<I>(&pairs));
        // A repeated submission gets the recorded reply; its handler does not
        // run. A claim whose request fails to decode is released afterwards.
        if let Some(key) = field(crate::replay::KEY).filter(|key| valid_key(key)) {
            let id = crate::replay::submission_id(key, &path, &headers, &[&body]);
            crate::native::claim(store, id).await?;
        }
        decode(&body).map(Self).map_err(|error| {
            (
                StatusCode::UNPROCESSABLE_ENTITY,
                format!("Failed to deserialize form body: {error}"),
            )
                .into_response()
        })
    }
}

fn valid_key(key: &str) -> bool {
    (16..=64).contains(&key.len()) && key.bytes().all(|byte| byte.is_ascii_alphanumeric())
}

/// Decode an urlencoded body or query string into its input. Repeated keys fill
/// `Vec` fields, an empty value is `None` for every `Option` field (including
/// `Option<String>`), and an absent bool is `false`, as for an unchecked checkbox.
/// Line breaks decode as LF, and reserved `placebo-` fields are removed.
pub(crate) fn decode<I: FormInput>(bytes: &[u8]) -> Result<I, serde_html_form::de::Error> {
    use private::Absent;
    let absent = |key: &str| {
        I::FIELDS
            .iter()
            .find(|(name, _)| *name == key)
            .map(|(_, absent)| *absent)
    };
    let mut pairs: Vec<_> = form_urlencoded::parse(bytes).collect();
    let before = pairs.len();
    pairs.retain(|(key, value)| {
        !key.starts_with(RESERVED) && (!value.is_empty() || absent(key) != Some(Absent::None))
    });
    // Browsers submit line breaks as CRLF; the runtime's requests keep LF.
    // Decode both as LF so a handler sees one value either way.
    let mut normalized = false;
    for (_, value) in &mut pairs {
        if value.contains('\r') {
            *value = value.replace("\r\n", "\n").replace('\r', "\n").into();
            normalized = true;
        }
    }
    let unchecked: Vec<_> = I::FIELDS
        .iter()
        .filter(|(name, absent)| {
            *absent == Absent::False && !pairs.iter().any(|(key, _)| key == name)
        })
        .map(|(name, _)| (*name, "false"))
        .collect();
    if pairs.len() == before && unchecked.is_empty() && !normalized {
        return serde_html_form::from_bytes(bytes);
    }
    let body = form_urlencoded::Serializer::new(String::new())
        .extend_pairs(&pairs)
        .extend_pairs(unchecked)
        .finish();
    serde_html_form::from_str(&body)
}

#[doc(hidden)]
pub mod private {
    use super::*;
    pub use maud::{Markup, html};
    pub struct Missing;
    pub struct Present;

    /// Implemented only by `#[derive(FormEnum)]`, which checks for unit variants.
    pub trait EnumSeal {}

    /// What an absent field means when a browser omits it from a submission.
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Absent {
        /// Serde decides: a missing-field error, or the field's serde default.
        Required,
        /// An unchecked checkbox: decoded as `false`.
        False,
        /// No selected options: requires `#[serde(default)]`, checked at compile time.
        Empty,
        /// Serde decodes a missing option as `None`.
        None,
    }

    /// Evaluated in a derive-generated constant for every field.
    pub const fn require_default(absent: Absent, has_default: bool) {
        if matches!(absent, Absent::Empty) && !has_default {
            panic!(
                "a Vec form field needs #[serde(default)]: browsers submit nothing when no option is selected"
            );
        }
    }

    #[derive(Default)]
    pub struct FormBuffer {
        html: String,
        base: Vec<(String, String)>,
    }

    /// Render one payload control. During a native submission's handler, a
    /// field the person edited shows what they submitted, as the runtime
    /// keeps an edited control, and the first invalid control takes focus.
    pub fn render_control<I: FormInput, T>(
        buffer: &mut FormBuffer,
        mut control: Control<T>,
        name: &str,
    ) {
        let edit = crate::native::resubmitted::<I>(name);
        if let Some(edit) = &edit {
            control.resubmit(&edit.values);
        }
        if control.invalid && crate::native::autofocus_invalid() {
            control.autofocus = true;
        }
        if let Some(values) = control.rendered_values() {
            let base = edit.map_or_else(|| fingerprint(&values), |edit| edit.base);
            buffer.base.push((name.to_owned(), base));
        }
        buffer.push(control.render_named(name));
    }

    impl FormBuffer {
        pub fn push(&mut self, markup: Markup) {
            self.html.push_str(&markup.into_string());
        }
        pub fn len(&self) -> usize {
            self.html.len()
        }
        pub fn is_empty(&self) -> bool {
            self.html.is_empty()
        }
        pub fn wrap_group(&mut self, start: usize, class: &str) {
            let content = PreEscaped(self.html.split_off(start));
            self.push(html! { div class=(class) { (content) } });
        }
        pub fn wrap_local(&mut self, start: usize, key: &str) {
            assert!(!key.is_empty(), "local state needs a key");
            let content = PreEscaped(self.html.split_off(start));
            self.push(html! { div data-placebo-local=(key) { (content) } });
        }
    }

    pub trait FormBuilder {
        type Input: FormInput;
        fn buffer(&mut self) -> &mut FormBuffer;
    }

    pub fn take_markup(builder: &mut impl FormBuilder) -> Markup {
        PreEscaped(std::mem::take(&mut builder.buffer().html))
    }

    pub fn finish<I: FormInput>(body: FormBuffer) -> FormFields<I> {
        FormFields {
            markup: PreEscaped(body.html),
            base: form_urlencoded::Serializer::new(String::new())
                .extend_pairs(&body.base)
                .finish(),
            input: PhantomData,
        }
    }
}
