//! Input-derived form builders. Controls render their own generated names;
//! completion requires every declared field, including fields with serde defaults.
use axum::{
    body::Bytes,
    extract::{FromRequest, FromRequestParts, Request},
    http::{StatusCode, header, request::Parts},
    response::{IntoResponse, Response},
};
use maud::{Markup, PreEscaped, html};
use serde::de::DeserializeOwned;
use std::{fmt::Display, marker::PhantomData};

#[doc = include_str!("../docs/typed-forms.md")]
pub trait FormInput: DeserializeOwned + Sized {
    type Builder: private::FormBuilder<Input = Self>;
    fn fields() -> Self::Builder;
    /// Wire names and absence rules, in declaration order. Generated by the derive.
    #[doc(hidden)]
    const FIELDS: &'static [(&'static str, private::Absent)];
}

/// A completed form for exactly one payload type. Constructed by finish() on
/// an input-derived builder after every field has been emitted once.
pub struct FormFields<I> {
    markup: Markup,
    input: PhantomData<fn() -> I>,
}

impl<I> FormFields<I> {
    pub(crate) fn into_markup(self) -> Markup {
        self.markup
    }
}

mod sealed {
    pub trait Value {}
    pub trait Field {}
}

/// Scalar values whose Display encoding matches their form deserialization.
pub trait FieldValue: sealed::Value + Display + DeserializeOwned {}

/// Every supported payload field type: a [`FieldValue`], an `Option` of one
/// (an empty or absent submission is `None`), or a `Vec` of one (repeated submissions).
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not a supported form field type",
    note = "form fields can be String, bool, integers, floats, Option<T> or Vec<T> of those"
)]
pub trait FormValue: sealed::Field + DeserializeOwned {
    #[doc(hidden)]
    const ABSENT: private::Absent;
}

/// A value submitted once by a single control: a scalar, or an optional scalar
/// encoded as an empty string when `None`.
pub trait SingleValue: FormValue {
    #[doc(hidden)]
    fn encode(&self) -> String;
}

/// Values for text-like inputs: `String`, or `Option<String>` where empty is `None`.
pub trait TextValue: SingleValue {}

/// Values for number inputs: integers, floats, or an optional one.
pub trait NumberValue: SingleValue {
    /// The attribute type for `min`, `max`, and `step`.
    type Number: Display;
    #[doc(hidden)]
    const STEP: Option<&'static str>;
}

macro_rules! scalars {
    ($absent:ident: $($ty:ty),* $(,)?) => { $(
        impl sealed::Value for $ty {}
        impl FieldValue for $ty {}
        impl sealed::Field for $ty {}
        impl FormValue for $ty { const ABSENT: private::Absent = private::Absent::$absent; }
        impl SingleValue for $ty { fn encode(&self) -> String { self.to_string() } }
        impl sealed::Field for Option<$ty> {}
        impl FormValue for Option<$ty> { const ABSENT: private::Absent = private::Absent::None; }
        impl SingleValue for Option<$ty> {
            fn encode(&self) -> String { self.as_ref().map(ToString::to_string).unwrap_or_default() }
        }
        impl sealed::Field for Vec<$ty> {}
        impl FormValue for Vec<$ty> { const ABSENT: private::Absent = private::Absent::Empty; }
    )* };
}
scalars!(Required: String, u8, u16, u32, u64, usize, i8, i16, i32, i64, isize, f32, f64);
// An unchecked checkbox submits nothing, so an absent bool decodes as false.
scalars!(False: bool);

impl TextValue for String {}
impl TextValue for Option<String> {}

macro_rules! numbers {
    ($step:expr => $($ty:ty),* $(,)?) => { $(
        impl NumberValue for $ty { type Number = $ty; const STEP: Option<&'static str> = $step; }
        impl NumberValue for Option<$ty> { type Number = $ty; const STEP: Option<&'static str> = $step; }
    )* };
}
numbers!(None => u8, u16, u32, u64, usize, i8, i16, i32, i64, isize);
// Browsers otherwise reject fractional values against the default step of 1.
numbers!(Some("any") => f32, f64);

enum Kind {
    Hidden(String),
    Text(String, &'static str),
    TextArea(String),
    Number(String),
    Checkbox(bool),
    Select(Vec<(String, String, bool)>),
    MultiSelect(Vec<(String, String, bool)>),
    Radios(Vec<(String, String, bool)>),
    Checkboxes(Vec<(String, String, bool)>),
}

/// A control with a payload value type. The builder supplies its field name;
/// there is no name override or disabled option that could remove it from submission.
pub struct Control<T> {
    kind: Kind,
    id: Option<String>,
    class: Option<String>,
    described_by: Option<String>,
    autocomplete: Option<String>,
    placeholder: Option<String>,
    rows: Option<u32>,
    min: Option<String>,
    max: Option<String>,
    step: Option<String>,
    value: PhantomData<fn() -> T>,
}

impl<T> Control<T> {
    fn new(kind: Kind) -> Self {
        Self {
            kind,
            id: None,
            class: None,
            described_by: None,
            autocomplete: None,
            placeholder: None,
            rows: None,
            min: None,
            max: None,
            step: None,
            value: PhantomData,
        }
    }

    /// For grouped controls (radios and checkboxes), this applies to the group element.
    pub fn id(mut self, id: &str) -> Self {
        self.id = Some(id.into());
        self
    }
    pub fn class(mut self, class: &str) -> Self {
        self.class = Some(class.into());
        self
    }
    pub fn described_by(mut self, id: &str) -> Self {
        self.described_by = Some(id.into());
        self
    }
    pub fn autocomplete(mut self, value: &str) -> Self {
        assert!(
            matches!(
                self.kind,
                Kind::Text(..) | Kind::TextArea(_) | Kind::Number(_) | Kind::Select(_)
            ),
            "autocomplete applies to text, textarea, number, and select controls"
        );
        self.autocomplete = Some(value.into());
        self
    }
    pub fn placeholder(mut self, value: &str) -> Self {
        assert!(
            matches!(
                self.kind,
                Kind::Text(..) | Kind::TextArea(_) | Kind::Number(_)
            ),
            "placeholder applies to text, textarea, and number controls"
        );
        self.placeholder = Some(value.into());
        self
    }
    pub fn rows(mut self, rows: u32) -> Self {
        assert!(
            matches!(self.kind, Kind::TextArea(_)),
            "rows applies to textarea controls"
        );
        self.rows = Some(rows);
        self
    }

    #[doc(hidden)]
    pub fn render_named(self, name: &str) -> Markup {
        let Self {
            kind,
            id,
            class,
            described_by,
            autocomplete,
            placeholder,
            rows,
            min,
            max,
            step,
            ..
        } = self;
        match kind {
            Kind::Hidden(value) => html! { input type="hidden" name=(name) value=(value); },
            Kind::Text(value, kind) => html! {
                input type=(kind) name=(name) value=(value) id=[id] class=[class]
                    aria-describedby=[described_by] autocomplete=[autocomplete] placeholder=[placeholder];
            },
            // The parser drops one newline after <textarea>, so emit our own to keep a leading one.
            Kind::TextArea(value) => html! {
                textarea name=(name) id=[id] class=[class] rows=[rows] aria-describedby=[described_by]
                    autocomplete=[autocomplete] placeholder=[placeholder] { "\n" (value) }
            },
            Kind::Number(value) => html! {
                input type="number" name=(name) value=(value) min=[min] max=[max] step=[step]
                    id=[id] class=[class] aria-describedby=[described_by]
                    autocomplete=[autocomplete] placeholder=[placeholder];
            },
            Kind::Checkbox(checked) => html! {
                input type="checkbox" name=(name) value="true" checked[checked] id=[id] class=[class]
                    aria-describedby=[described_by];
            },
            Kind::Select(options) => html! {
                select name=(name) id=[id] class=[class] aria-describedby=[described_by] autocomplete=[autocomplete] {
                    @for (value, label, selected) in options {
                        option value=(value) selected[selected] { (label) }
                    }
                }
            },
            Kind::MultiSelect(options) => html! {
                select multiple name=(name) id=[id] class=[class] aria-describedby=[described_by] {
                    @for (value, label, selected) in options {
                        option value=(value) selected[selected] { (label) }
                    }
                }
            },
            Kind::Radios(options) => html! {
                div role="radiogroup" id=[id] class=[class] aria-describedby=[described_by] {
                    @for (value, label, checked) in options {
                        label { input type="radio" name=(name) value=(value) checked[checked]; " " (label) }
                    }
                }
            },
            Kind::Checkboxes(options) => html! {
                div role="group" id=[id] class=[class] aria-describedby=[described_by] {
                    @for (value, label, checked) in options {
                        label { input type="checkbox" name=(name) value=(value) checked[checked]; " " (label) }
                    }
                }
            },
        }
    }
}

fn options<T: SingleValue + PartialEq, L: Into<String>>(
    options: impl IntoIterator<Item = (T, L)>,
    selected: impl Fn(&T) -> bool,
) -> Vec<(String, String, bool)> {
    options
        .into_iter()
        .map(|(value, label)| {
            let is_selected = selected(&value);
            (value.encode(), label.into(), is_selected)
        })
        .collect()
}

fn is_none<T: SingleValue>(value: &T) -> bool {
    matches!(T::ABSENT, private::Absent::None) && value.encode().is_empty()
}

impl<T: SingleValue> Control<T> {
    pub fn hidden(value: T) -> Self {
        Self::new(Kind::Hidden(value.encode()))
    }

    pub fn select<L: Into<String>>(selected: T, options: impl IntoIterator<Item = (T, L)>) -> Self
    where
        T: PartialEq,
    {
        let options = self::options(options, |value| *value == selected);
        assert!(
            options.iter().any(|(_, _, selected)| *selected),
            "a select needs an option matching its initial value"
        );
        Self::new(Kind::Select(options))
    }

    /// One labeled radio button per option, inside a `radiogroup` element.
    /// An optional field may start as `None` with no option checked.
    pub fn radios<L: Into<String>>(selected: T, options: impl IntoIterator<Item = (T, L)>) -> Self
    where
        T: PartialEq,
    {
        let options = self::options(options, |value| *value == selected);
        assert!(
            is_none(&selected) || options.iter().any(|(_, _, selected)| *selected),
            "radios need an option matching their initial value"
        );
        Self::new(Kind::Radios(options))
    }
}

impl<T: TextValue> Control<T> {
    pub fn text(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "text")
    }
    pub fn search(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "search")
    }
    pub fn email(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "email")
    }
    pub fn url(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "url")
    }
    pub fn tel(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "tel")
    }
    /// A `YYYY-MM-DD` string; parse and validate it in the handler.
    pub fn date(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "date")
    }
    /// An `HH:MM` or `HH:MM:SS` string.
    pub fn time(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "time")
    }
    /// A `YYYY-MM-DDTHH:MM` string without a time zone.
    pub fn datetime_local(value: impl Into<T>) -> Self {
        Self::text_kind(value.into(), "datetime-local")
    }
    /// Always renders empty: a server response never echoes a password into markup.
    pub fn password() -> Self {
        Self::new(Kind::Text(String::new(), "password"))
    }
    pub fn textarea(value: impl Into<T>) -> Self {
        Self::new(Kind::TextArea(value.into().encode()))
    }

    fn text_kind(value: T, kind: &'static str) -> Self {
        Self::new(Kind::Text(value.encode(), kind))
    }
}

impl<T: NumberValue> Control<T> {
    /// Float fields default to `step="any"`; integer fields use the browser's step of 1.
    pub fn number(value: T) -> Self {
        let mut control = Self::new(Kind::Number(value.encode()));
        control.step = T::STEP.map(Into::into);
        control
    }
    pub fn min(mut self, value: T::Number) -> Self {
        self.assert_number();
        self.min = Some(value.to_string());
        self
    }
    pub fn max(mut self, value: T::Number) -> Self {
        self.assert_number();
        self.max = Some(value.to_string());
        self
    }
    pub fn step(mut self, value: T::Number) -> Self {
        self.assert_number();
        self.step = Some(value.to_string());
        self
    }

    fn assert_number(&self) {
        assert!(
            matches!(self.kind, Kind::Number(_)),
            "min, max, and step apply to number controls"
        );
    }
}

impl Control<bool> {
    /// Submits `true` when checked. An unchecked box submits nothing, which the
    /// typed adapters decode as `false`.
    pub fn checkbox(checked: bool) -> Self {
        Self::new(Kind::Checkbox(checked))
    }
}

impl<T: FieldValue + SingleValue + PartialEq> Control<Vec<T>> {
    /// A `<select multiple>`. Every selected value must be one of the options.
    pub fn multi_select<L: Into<String>>(
        selected: impl IntoIterator<Item = T>,
        options: impl IntoIterator<Item = (T, L)>,
    ) -> Self {
        Self::new(Kind::MultiSelect(many(selected, options)))
    }

    /// One labeled checkbox per option, inside a `group` element.
    pub fn checkboxes<L: Into<String>>(
        selected: impl IntoIterator<Item = T>,
        options: impl IntoIterator<Item = (T, L)>,
    ) -> Self {
        Self::new(Kind::Checkboxes(many(selected, options)))
    }
}

fn many<T: SingleValue + PartialEq, L: Into<String>>(
    selected: impl IntoIterator<Item = T>,
    options: impl IntoIterator<Item = (T, L)>,
) -> Vec<(String, String, bool)> {
    let selected: Vec<T> = selected.into_iter().collect();
    let options = self::options(options, |value| selected.contains(value));
    assert_eq!(
        options.iter().filter(|(_, _, selected)| *selected).count(),
        selected.len(),
        "every selected value needs exactly one matching option"
    );
    options
}

/// A mutation body decoded with [`decode`]. Rejections match axum's `Form`:
/// 415 for another content type and 422 for a payload that does not decode.
pub(crate) struct FormBody<I>(pub I);

impl<I: FormInput, S: Send + Sync> FromRequest<S> for FormBody<I> {
    type Rejection = Response;

    async fn from_request(request: Request, state: &S) -> Result<Self, Self::Rejection> {
        let form = request
            .headers()
            .get(header::CONTENT_TYPE)
            .and_then(|value| value.to_str().ok())
            .and_then(|value| value.split(';').next())
            .is_some_and(|mime| {
                mime.trim()
                    .eq_ignore_ascii_case("application/x-www-form-urlencoded")
            });
        if !form {
            return Err((
                StatusCode::UNSUPPORTED_MEDIA_TYPE,
                "Expected request with `Content-Type: application/x-www-form-urlencoded`",
            )
                .into_response());
        }
        let body = Bytes::from_request(request, state)
            .await
            .map_err(IntoResponse::into_response)?;
        decode(&body).map(Self).map_err(|error| {
            (
                StatusCode::UNPROCESSABLE_ENTITY,
                format!("Failed to deserialize form body: {error}"),
            )
                .into_response()
        })
    }
}

/// A read query decoded with [`decode`]. Rejects with 400, like axum's `Query`.
pub(crate) struct QueryInput<I>(pub I);

impl<I: FormInput, S: Send + Sync> FromRequestParts<S> for QueryInput<I> {
    type Rejection = (StatusCode, String);

    async fn from_request_parts(parts: &mut Parts, _: &S) -> Result<Self, Self::Rejection> {
        decode(parts.uri.query().unwrap_or_default().as_bytes())
            .map(Self)
            .map_err(|error| {
                (
                    StatusCode::BAD_REQUEST,
                    format!("Failed to deserialize query string: {error}"),
                )
            })
    }
}

/// Decode an urlencoded body or query string into its input. Repeated keys fill
/// `Vec` fields, an empty value is `None` for every `Option` field (including
/// `Option<String>`), and an absent bool is `false`, as for an unchecked checkbox.
pub(crate) fn decode<I: FormInput>(bytes: &[u8]) -> Result<I, serde_html_form::de::Error> {
    use private::Absent;
    let absent = |key: &str| {
        I::FIELDS
            .iter()
            .find(|(name, _)| *name == key)
            .map(|(_, absent)| *absent)
    };
    let mut pairs: Vec<_> = form_urlencoded::parse(bytes).collect();
    let before = pairs.len();
    pairs.retain(|(key, value)| !value.is_empty() || absent(key) != Some(Absent::None));
    let unchecked: Vec<_> = I::FIELDS
        .iter()
        .filter(|(name, absent)| {
            *absent == Absent::False && !pairs.iter().any(|(key, _)| key == name)
        })
        .map(|(name, _)| (*name, "false"))
        .collect();
    if pairs.len() == before && unchecked.is_empty() {
        return serde_html_form::from_bytes(bytes);
    }
    let body = form_urlencoded::Serializer::new(String::new())
        .extend_pairs(&pairs)
        .extend_pairs(unchecked)
        .finish();
    serde_html_form::from_str(&body)
}

#[doc(hidden)]
pub mod private {
    use super::*;
    pub use maud::{Markup, html};
    pub struct Missing;
    pub struct Present;

    /// What an absent field means when a browser omits it from a submission.
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Absent {
        /// Serde decides: a missing-field error, or the field's serde default.
        Required,
        /// An unchecked checkbox: decoded as `false`.
        False,
        /// No selected options: requires `#[serde(default)]`, checked at compile time.
        Empty,
        /// Serde decodes a missing option as `None`.
        None,
    }

    /// Evaluated in a derive-generated constant for every field.
    pub const fn require_default(absent: Absent, has_default: bool) {
        if matches!(absent, Absent::Empty) && !has_default {
            panic!(
                "a Vec form field needs #[serde(default)]: browsers submit nothing when no option is selected"
            );
        }
    }

    #[derive(Default)]
    pub struct FormBuffer {
        html: String,
    }

    impl FormBuffer {
        pub fn push(&mut self, markup: Markup) {
            self.html.push_str(&markup.into_string());
        }
        pub fn len(&self) -> usize {
            self.html.len()
        }
        pub fn is_empty(&self) -> bool {
            self.html.is_empty()
        }
        pub fn wrap_group(&mut self, start: usize, class: &str) {
            let content = PreEscaped(self.html.split_off(start));
            self.push(html! { div class=(class) { (content) } });
        }
        pub fn wrap_local(&mut self, start: usize, key: &str) {
            assert!(!key.is_empty(), "local state needs a key");
            let content = PreEscaped(self.html.split_off(start));
            self.push(html! { div data-placebo-local=(key) { (content) } });
        }
    }

    pub trait FormBuilder {
        type Input: FormInput;
        fn buffer(&mut self) -> &mut FormBuffer;
    }

    pub fn take_markup(builder: &mut impl FormBuilder) -> Markup {
        PreEscaped(std::mem::take(&mut builder.buffer().html))
    }

    pub fn finish<I: FormInput>(body: FormBuffer) -> FormFields<I> {
        FormFields {
            markup: PreEscaped(body.html),
            input: PhantomData,
        }
    }
}
